window.MOCK_DEALS = [
  {
    id: 1,
    name: 'Nước giặt OMO Matic túi 3.6kg',
    category: 'Giặt giũ',
    essential: true,
    price: 189000,
    oldPrice: 269000,
    unit: '52.500đ/kg',
    discountPercent: 29,
    rating: 4.9,
    sold: 12400,
    shop: 'OMO Official Store',
    shopType: 'Mall',
    freeShip: true,
    voucher: 'Giảm thêm 15k',
    dealScore: 93,
    status: 'buy',
    emoji: '🧺',
    note: 'Giá/kg tốt, phù hợp mua định kỳ',
  },
  {
    id: 2,
    name: 'Giấy vệ sinh Pulppy 24 cuộn 4 lớp',
    category: 'Giấy & vệ sinh',
    essential: true,
    price: 119000,
    oldPrice: 165000,
    unit: '4.958đ/cuộn',
    discountPercent: 28,
    rating: 4.8,
    sold: 9800,
    shop: 'Pulppy Official',
    shopType: 'Mall',
    freeShip: true,
    voucher: 'Freeship Xtra',
    dealScore: 91,
    status: 'buy',
    emoji: '🧻',
    note: 'Món thiết yếu, giá/cuộn đang khá đẹp',
  },
  {
    id: 3,
    name: 'Nước rửa chén Sunlight 3.6kg túi',
    category: 'Nhà bếp',
    essential: true,
    price: 98000,
    oldPrice: 135000,
    unit: '27.222đ/kg',
    discountPercent: 27,
    rating: 4.8,
    sold: 7300,
    shop: 'Sunlight Home Care',
    shopType: 'Mall',
    freeShip: true,
    voucher: 'Combo gia đình',
    dealScore: 88,
    status: 'buy',
    emoji: '🍽️',
    note: 'Rất hợp gom chung với nước giặt để tối ưu ship',
  },
  {
    id: 4,
    name: 'Nước lau sàn Gift hương chanh 3.8L',
    category: 'Vệ sinh nhà cửa',
    essential: true,
    price: 79000,
    oldPrice: 109000,
    unit: '20.789đ/L',
    discountPercent: 28,
    rating: 4.7,
    sold: 4100,
    shop: 'Gift Official',
    shopType: 'Mall',
    freeShip: false,
    voucher: 'Mua 2 giảm 10k',
    dealScore: 80,
    status: 'wait',
    emoji: '🧼',
    note: 'Ổn nhưng chưa phải đáy đẹp nhất',
  },
  {
    id: 5,
    name: 'Khăn giấy ăn Bless You 10 gói',
    category: 'Giấy & vệ sinh',
    essential: true,
    price: 45000,
    oldPrice: 62000,
    unit: '4.500đ/gói',
    discountPercent: 27,
    rating: 4.8,
    sold: 6500,
    shop: 'Bless You Store',
    shopType: 'Yêu thích+',
    freeShip: true,
    voucher: 'Voucher shop 5k',
    dealScore: 84,
    status: 'buy',
    emoji: '📦',
    note: 'Giá rẻ, dễ add-on vào đơn lớn',
  },
  {
    id: 6,
    name: 'Nước xả Comfort 3.2L đậm đặc',
    category: 'Giặt giũ',
    essential: true,
    price: 154000,
    oldPrice: 199000,
    unit: '48.125đ/L',
    discountPercent: 23,
    rating: 4.9,
    sold: 5400,
    shop: 'Comfort Official',
    shopType: 'Mall',
    freeShip: true,
    voucher: 'Giảm 12k đơn từ 149k',
    dealScore: 85,
    status: 'buy',
    emoji: '🌸',
    note: 'Tốt nếu mua kèm nước giặt',
  },
  {
    id: 7,
    name: 'Túi rác gia đình tự huỷ 3 cuộn',
    category: 'Vệ sinh nhà cửa',
    essential: true,
    price: 39000,
    oldPrice: 52000,
    unit: '13.000đ/cuộn',
    discountPercent: 25,
    rating: 4.7,
    sold: 2300,
    shop: 'Home Basic VN',
    shopType: 'Yêu thích',
    freeShip: false,
    voucher: 'Giảm 8%',
    dealScore: 73,
    status: 'wait',
    emoji: '🗑️',
    note: 'Được nhưng nên đợi freeship',
  },
  {
    id: 8,
    name: 'Bình xịt lau bếp đa năng 500ml',
    category: 'Nhà bếp',
    essential: true,
    price: 59000,
    oldPrice: 89000,
    unit: '118.000đ/L',
    discountPercent: 34,
    rating: 4.6,
    sold: 1800,
    shop: 'Clean Kitchen',
    shopType: 'Yêu thích+',
    freeShip: true,
    voucher: 'Mua 2 giảm 5k',
    dealScore: 76,
    status: 'wait',
    emoji: '✨',
    note: 'Giảm đẹp nhưng giá/L vẫn chưa quá xuất sắc',
  },
  {
    id: 9,
    name: 'Combo bàn chải + kem đánh răng gia đình',
    category: 'Chăm sóc cá nhân',
    essential: true,
    price: 99000,
    oldPrice: 149000,
    unit: 'Combo tiết kiệm',
    discountPercent: 34,
    rating: 4.8,
    sold: 5200,
    shop: 'Family Care Mall',
    shopType: 'Mall',
    freeShip: true,
    voucher: 'Giảm thêm 10k',
    dealScore: 82,
    status: 'buy',
    emoji: '🪥',
    note: 'Đồ tiêu hao nên khá hợp để săn sale',
  },
  {
    id: 10,
    name: 'Hộp đựng thực phẩm 10 món',
    category: 'Gia dụng',
    essential: false,
    price: 129000,
    oldPrice: 189000,
    unit: '12.900đ/món',
    discountPercent: 32,
    rating: 4.7,
    sold: 3100,
    shop: 'Nhà Bếp Gọn Gàng',
    shopType: 'Yêu thích+',
    freeShip: true,
    voucher: 'Giảm 15k',
    dealScore: 69,
    status: 'wait',
    emoji: '🥡',
    note: 'Không phải thiết yếu nhất nên ưu tiên thấp hơn',
  }
];
